import { escapeHtml } from '../app/html'
import { addAdult, adultsForLearner, authenticateAdult, classesForLearner, classesForTeacher, createClassGroup, getParentControls, removeAdult, removeClassGroup, setAdultCredentials, setAdultsForLearner, updateAdultProfile } from '../app/parent-controls'
import { authenticateAccount, addLearner, getLearners, getSettings, removeLearner, setActiveLearner, setGuardianCredentials, setLearnerCredentials, updateLearnerProfile, updateOwnerAccount } from '../app/store'
import { isAdministrator, setSignedInUser } from '../app/session'
import { getTheme, setTheme, themes } from '../app/themes'
import { renderLearnerModules, renderLearnerProgressMaterial } from './admin-learning-controls'
import { wireLearnerLearningControls } from './admin-learning-controls-wire'
import { getApp, resetNavigation } from '../nav'
import { renderHome } from './home'
import { renderParentDashboard } from './parent-controls'
import { renderTeacherTools } from './teacher-tools'
import { renderFamilyHub } from './family-hub'

const avatars = ['🌟', '🦊', '🐳', '🦄', '🚀', '🌈']

export function renderProfilePicker() {
  getApp().innerHTML = `<main class="profile-picker"><section class="profile-welcome login-welcome"><div class="profile-brand"><span class="profile-brand-mark"></span><div>LearnOS</div></div><p class="os-kicker">LOCAL LEARNING ENVIRONMENT</p><h1>Choose your learning space</h1><p>Sign in with your own account. Learners, parents, guardians, and teachers each enter through the workspace made for them.</p></section><section class="profile-selection login-selection"><form id="account-login" class="profile-add-form account-login"><div><p class="os-kicker">SIGN IN</p><h2>Welcome back</h2></div><label>Username<input id="account-username" required maxlength="40" autocomplete="username" placeholder="Your username"></label><label>Password<input id="account-password" type="password" required minlength="8" maxlength="128" autocomplete="current-password" placeholder="Your password"></label><button class="os-primary">Enter LearnOS</button><p class="parent-error" id="account-login-error" aria-live="polite"></p></form><aside class="profile-add-form login-note"><p class="os-kicker">ONE ACCOUNT, ONE SPACE</p><h2>Role-based access</h2><p>Parents and guardians manage people, access, and learning plans. Teachers open teaching tools. Learners open their own learning hub.</p><small>Administrators create and manage local accounts after they sign in.</small></aside></section></main>`
  document.querySelector('.login-welcome .os-kicker')!.textContent = 'LOCAL-FIRST • PRIVATE BY DEFAULT'
  document.querySelector('.login-welcome h1')!.textContent = 'Local Learning Environment'
  document.getElementById('account-login')!.addEventListener('submit', async event => {
    event.preventDefault()
    const username = (document.getElementById('account-username') as HTMLInputElement).value
    const password = (document.getElementById('account-password') as HTMLInputElement).value
    const account = await authenticateAccount(username, password)
    const adult = account ? null : await authenticateAdult(username, password)
    ;(document.getElementById('account-password') as HTMLInputElement).value = ''
    if (account?.role === 'Learner' && account.learnerId) { setSignedInUser({ role: 'Learner', name: username, accountKey: `learner:${account.learnerId}` }); setActiveLearner(account.learnerId); resetNavigation(renderHome); return }
    if (account?.role === 'Admin') { setSignedInUser({ role: 'Admin', name: username, accountKey: 'admin:owner' }); if (account.ownerBootstrap) { renderOwnerBootstrap(); return } resetNavigation(renderParentDashboard); return }
    if (adult?.role === 'Teacher') { setSignedInUser({ role: 'Teacher', name: adult.name, accountKey: `adult:${adult.id}` }); resetNavigation(renderTeacherTools); return }
    if (adult) { setSignedInUser({ role: adult.role, name: adult.name, accountKey: `adult:${adult.id}` }); resetNavigation(renderFamilyHub); return }
    document.getElementById('account-login-error')!.textContent = 'We could not verify that username and password.'
  })
}

export function renderProfileSettings() {
  if (isAdministrator()) renderUserManagement()
  else renderProfilePicker()
}

export function openUserManagement(compose: 'view' | 'learner' | 'staff' | 'family' = 'view') {
  renderUserManagement('', 'all', 'all', '', [], compose)
}

function renderOwnerBootstrap() {
  getApp().innerHTML = `<main class="parent-gate"><section class="parent-gate-card"><p class="os-kicker">ULTIMATE OWNER</p><h1>Secure your owner account</h1><p>You entered the initial local owner account. Choose a private password before opening administration.</p><form id="owner-bootstrap-form" autocomplete="off"><input id="owner-bootstrap-password" type="password" minlength="8" maxlength="128" required autocomplete="new-password" placeholder="New owner password"><button class="os-primary">Secure & enter administration</button></form><p class="parent-error" id="owner-bootstrap-error"></p></section></main>`
  document.getElementById('owner-bootstrap-form')!.addEventListener('submit', async event => { event.preventDefault(); const password = (document.getElementById('owner-bootstrap-password') as HTMLInputElement).value; if (await setGuardianCredentials('admin', password)) resetNavigation(renderParentDashboard); else document.getElementById('owner-bootstrap-error')!.textContent = 'Use a password with at least eight characters.' })
}

type AdminRole = 'Admin' | 'Guardian' | 'Parent' | 'Teacher' | 'Learner'
type AdminAccount = { key: string; id: string; kind: 'guardian' | 'adult' | 'learner'; role: AdminRole; name: string; username: string; stage: string; avatar: string; credentialReady: boolean }

function renderUserManagement(query = '', roleFilter = 'all', stageFilter = 'all', selectedKey = '', selectedKeys: string[] = [], compose: 'view' | 'learner' | 'staff' | 'family' = 'view') {
  const learners = getLearners()
  const adults = getParentControls().adults
  const settings = getSettings()
  const accounts: AdminAccount[] = [
    { key: 'admin:owner', id: 'owner', kind: 'guardian', role: 'Admin', name: settings?.householdName ?? 'Learning home', username: settings?.guardianUsername ?? '', stage: 'Ultimate owner', avatar: 'A', credentialReady: Boolean(settings?.guardianUsername && settings?.guardianPasswordHash) },
    ...adults.map(adult => ({ key: `adult:${adult.id}`, id: adult.id, kind: 'adult' as const, role: adult.role, name: adult.name, username: adult.username ?? '', stage: 'Staff account', avatar: adult.name.slice(0, 1).toUpperCase(), credentialReady: Boolean(adult.username && adult.passwordHash) })),
    ...learners.map(learner => ({ key: `learner:${learner.id}`, id: learner.id, kind: 'learner' as const, role: 'Learner' as const, name: learner.name, username: learner.username ?? '', stage: learner.ageBand, avatar: learner.avatar, credentialReady: Boolean(learner.username && learner.passwordHash) })),
  ]
  const stages = [...new Set(learners.map(learner => learner.ageBand))].sort()
  const normalizedQuery = query.trim().toLocaleLowerCase()
  const visible = accounts.filter(account => (roleFilter === 'all' || account.role.toLowerCase() === roleFilter) && (stageFilter === 'all' || account.stage === stageFilter) && (!normalizedQuery || `${account.name} ${account.username} ${account.role} ${account.stage}`.toLocaleLowerCase().includes(normalizedQuery)))
  const selected = accounts.find(account => account.key === selectedKey) ?? visible[0] ?? accounts[0]
  const selectedSet = new Set(selectedKeys.filter(key => visible.some(account => account.key === key)))
  const rosterRows = visible.length ? visible.map(account => `<button class="roster-row ${selected?.key === account.key ? 'is-active' : ''}" data-account-select="${escapeHtml(account.key)}"><input type="checkbox" data-account-mark="${escapeHtml(account.key)}" ${selectedSet.has(account.key) ? 'checked' : ''} aria-label="Select ${escapeHtml(account.name)}"><span class="roster-avatar">${escapeHtml(account.avatar)}</span><span class="roster-name"><strong>${escapeHtml(account.name)}</strong><small>${escapeHtml(account.username || 'Username not set')}</small></span><span class="roster-stage">${escapeHtml(account.stage)}</span><span class="roster-role role-${account.role.toLowerCase()}">${escapeHtml(account.role)}</span><span class="account-status ${account.credentialReady ? 'ready' : 'setup'}">${account.credentialReady ? 'Ready' : 'Set up'}</span></button>`).join('') : '<p class="roster-empty">No accounts match these filters.</p>'
  const summary = `<div class="admin-metrics"><span><strong>${learners.length}</strong>Learners</span><span><strong>${adults.filter(adult => adult.role === 'Teacher').length}</strong>Teachers</span><span><strong>${accounts.filter(account => account.credentialReady).length}</strong>Ready to sign in</span></div>`
  const selectedInfo = selected ? renderAccountInspector(selected, compose) : '<div class="inspector-empty"><h2>No account selected</h2><p>Change your search or filters to find a person.</p></div>'
  getApp().innerHTML = `<main class="parent-dashboard user-management admin-directory"><header><button class="back-btn" id="user-admin-done">← Admin Corner</button><div><p class="os-kicker">ADMINISTRATION</p><h1>People & access</h1><p>Admin controls staff, family accounts, and learner access from one local roster.</p></div><div class="admin-header-actions"><button class="os-primary" id="add-learner-button">Add learner</button><button class="os-secondary" id="add-staff-button">Add staff</button></div></header>${summary}<section class="admin-workspace"><article class="roster-panel"><div class="roster-toolbar"><label class="roster-search"><span>Search</span><input id="roster-search" value="${escapeHtml(query)}" placeholder="Name, username, grade, or role"></label><label><span>Role</span><select id="roster-role"><option value="all">All roles</option><option value="admin" ${roleFilter === 'admin' ? 'selected' : ''}>Admin</option><option value="learner" ${roleFilter === 'learner' ? 'selected' : ''}>Learners</option><option value="teacher" ${roleFilter === 'teacher' ? 'selected' : ''}>Teachers</option><option value="parent" ${roleFilter === 'parent' ? 'selected' : ''}>Parents</option><option value="guardian" ${roleFilter === 'guardian' ? 'selected' : ''}>Guardians</option></select></label><label><span>Grade / stage</span><select id="roster-stage"><option value="all">All stages</option>${stages.map(stage => `<option value="${escapeHtml(stage)}" ${stageFilter === stage ? 'selected' : ''}>${escapeHtml(stage)}</option>`).join('')}</select></label></div><div class="roster-meta"><strong>${visible.length} of ${accounts.length} people</strong>${selectedSet.size ? `<span>${selectedSet.size} selected <button class="text-button" id="clear-roster-selection">Clear</button></span>` : '<span>Select rows to prepare a cohort.</span>'}</div><div class="roster-columns"><span></span><span>Person</span><span>Stage</span><span>Role</span><span>Status</span></div><div class="roster-list">${rosterRows}</div></article><aside class="account-inspector">${selectedInfo}</aside></section></main>`
  const rerender = (nextQuery = query, nextRole = roleFilter, nextStage = stageFilter, nextSelected = selected?.key ?? '', nextMarked = [...selectedSet], nextCompose = compose) => renderUserManagement(nextQuery, nextRole, nextStage, nextSelected, nextMarked, nextCompose)
  const entryPanel = document.querySelector('.account-inspector')!
  entryPanel.insertAdjacentHTML('afterbegin', `<div class="account-entry-switch"><span>Add to directory</span><div><button class="${compose === 'learner' ? 'is-active' : ''}" data-entry-compose="learner">Learner</button><button class="${compose === 'family' ? 'is-active' : ''}" data-entry-compose="family">Family</button><button class="${compose === 'staff' ? 'is-active' : ''}" data-entry-compose="staff">Staff</button></div></div>`)
  document.getElementById('user-admin-done')!.addEventListener('click', () => renderParentDashboard())
  document.querySelector('.admin-header-actions')?.remove()
  document.querySelectorAll<HTMLButtonElement>('[data-entry-compose]').forEach(button => button.addEventListener('click', () => rerender(query, roleFilter, stageFilter, '', [...selectedSet], button.dataset.entryCompose as 'learner' | 'staff' | 'family')))
  document.getElementById('roster-search')!.addEventListener('input', event => rerender((event.target as HTMLInputElement).value, roleFilter, stageFilter, '', [...selectedSet]))
  document.getElementById('roster-role')!.addEventListener('change', event => rerender(query, (event.target as HTMLSelectElement).value, stageFilter, '', [...selectedSet]))
  document.getElementById('roster-stage')!.addEventListener('change', event => rerender(query, roleFilter, (event.target as HTMLSelectElement).value, '', [...selectedSet]))
  document.getElementById('clear-roster-selection')?.addEventListener('click', () => rerender(query, roleFilter, stageFilter, selected?.key, []))
  document.querySelectorAll<HTMLButtonElement>('[data-account-select]').forEach(row => row.addEventListener('click', event => { if ((event.target as HTMLElement).matches('[data-account-mark]')) return; rerender(query, roleFilter, stageFilter, row.dataset.accountSelect!, [...selectedSet]) }))
  document.querySelectorAll<HTMLInputElement>('[data-account-mark]').forEach(input => input.addEventListener('change', () => { input.checked ? selectedSet.add(input.dataset.accountMark!) : selectedSet.delete(input.dataset.accountMark!); rerender(query, roleFilter, stageFilter, selected?.key, [...selectedSet]) }))
  wireAccountInspector(selected, rerender)
}

function renderAccountInspector(account: AdminAccount, compose: 'view' | 'learner' | 'staff' | 'family') {
  if (compose === 'learner') return `<div class="inspector-heading"><p class="os-kicker">NEW ACCOUNT</p><h2>Add learner</h2><p>Create a local learner sign-in. You can assign modules and access after the account is created.</p></div><form id="add-learner-account" class="inspector-form"><label>Name<input id="learner-name" required maxlength="30"></label><label>Age / grade band<input id="learner-age" required maxlength="40" placeholder="Grade 3"></label><label>Companion<select id="learner-avatar">${avatars.map(avatar => `<option>${avatar}</option>`).join('')}</select></label><label>Username<input id="learner-username" required maxlength="40" autocomplete="username"></label><label>Temporary password<input id="learner-password" required type="password" minlength="8" maxlength="128" autocomplete="new-password"></label><button class="os-primary">Create learner account</button></form>`
  if (compose === 'staff' || compose === 'family') return `<div class="inspector-heading"><p class="os-kicker">NEW ACCOUNT</p><h2>${compose === 'family' ? 'Add family account' : 'Add staff'}</h2><p>${compose === 'family' ? 'Create a parent or guardian account, then link it permanently to a learner.' : 'Create a parent, guardian, or teacher account with its own local sign-in.'}</p></div><form id="add-adult-account" class="inspector-form"><label>Name<input id="adult-name" required maxlength="50"></label><label>Role<select id="adult-role"><option ${compose === 'staff' ? 'selected' : ''}>Teacher</option><option ${compose === 'family' ? 'selected' : ''}>Parent</option><option>Guardian</option></select></label><label>Username<input id="adult-username" required maxlength="40" autocomplete="username"></label><label>Temporary password<input id="adult-password" required type="password" minlength="8" maxlength="128" autocomplete="new-password"></label><button class="os-primary">Create ${compose === 'family' ? 'family' : 'staff'} account</button></form>`
  const status = account.credentialReady ? 'This account can sign in.' : 'This account needs a username and password.'
  const credentialsForm = account.kind === 'guardian' ? `<form id="guardian-credentials" class="inspector-form"><p class="os-kicker">ACCOUNT SETTINGS</p><label>Account name<input id="guardian-name" required maxlength="80" value="${escapeHtml(account.name)}"></label><label>Username<input id="guardian-username" required maxlength="40" value="${escapeHtml(account.username)}" autocomplete="username"></label><label>New password <small>leave blank to keep the current password</small><input id="guardian-password" type="password" minlength="8" maxlength="128" autocomplete="new-password"></label><button class="os-primary">Save account settings</button><p class="parent-error" id="guardian-credentials-error"></p></form>` : `<form id="account-credentials" class="inspector-form"><label>Username<input id="selected-username" required maxlength="40" value="${escapeHtml(account.username)}"></label><label>New password <small>leave blank to keep the current password</small><input id="selected-password" type="password" minlength="8" maxlength="128" autocomplete="new-password"></label><button class="os-primary">Save credentials</button><p class="parent-error" id="selected-credentials-error"></p></form>`
  const profileForm = account.kind === 'learner' ? `<form id="edit-account-profile" class="inspector-form account-profile-form"><p class="os-kicker">CORE RECORD</p><label>Name<input id="profile-name" required maxlength="30" value="${escapeHtml(account.name)}"></label><label>Grade / stage<input id="profile-stage" required maxlength="40" value="${escapeHtml(account.stage)}"></label><label>Companion<select id="profile-avatar">${avatars.map(avatar => `<option ${avatar === account.avatar ? 'selected' : ''}>${avatar}</option>`).join('')}</select></label><button class="os-secondary">Save record</button><p class="parent-error" id="profile-error"></p></form>` : account.kind === 'adult' ? `<form id="edit-account-profile" class="inspector-form account-profile-form"><p class="os-kicker">CORE RECORD</p><label>Name<input id="profile-name" required maxlength="50" value="${escapeHtml(account.name)}"></label><label>Role<select id="profile-role"><option ${account.role === 'Parent' ? 'selected' : ''}>Parent</option><option ${account.role === 'Guardian' ? 'selected' : ''}>Guardian</option><option ${account.role === 'Teacher' ? 'selected' : ''}>Teacher</option></select></label><button class="os-secondary">Save record</button><p class="parent-error" id="profile-error"></p></form>` : ''
  const learnerControls = account.kind === 'learner' ? `<label class="inspector-theme">Learning theme<select id="selected-theme">${themes.filter(([id]) => id !== 'dark').map(([id, name]) => `<option value="${id}" ${getTheme(account.id) === id ? 'selected' : ''}>${name}</option>`).join('')}</select></label>${renderLearnerAdultTeam(account.id)}${renderLearnerClasses(account.id)}${renderLearnerModules(account.id)}${renderLearnerProgressMaterial(account.id)}` : account.kind === 'adult' && account.role === 'Teacher' ? renderTeacherClasses(account.id) : ''
  const remove = account.kind === 'learner' ? `<button class="text-button danger-action" id="remove-selected-learner">Remove learner account</button>` : account.kind === 'adult' ? `<button class="text-button danger-action" id="remove-selected-adult">Remove staff account</button>` : ''
  return `<div class="inspector-heading"><span class="inspector-avatar">${escapeHtml(account.avatar)}</span><div><p class="os-kicker">${escapeHtml(account.role)} ACCOUNT</p><h2>${escapeHtml(account.name)}</h2><p>${escapeHtml(account.stage)}</p></div></div><div class="inspector-status ${account.credentialReady ? 'ready' : 'setup'}"><strong>${account.credentialReady ? 'Sign-in ready' : 'Setup needed'}</strong><span>${status}</span></div>${profileForm}${learnerControls}${credentialsForm}${remove}`
}

function renderLearnerAdultTeam(learnerId: string) {
  const adults = getParentControls().adults
  const assigned = new Set(adultsForLearner(learnerId).map(adult => adult.id))
  if (!adults.length) return `<section class="learner-team"><h3>Profile links</h3><p>Add a parent, guardian, or teacher account first, then link them to this learner here.</p></section>`
  return `<section class="learner-team"><div><p class="os-kicker">PERMANENT PROFILE LINKS</p><h3>Parents, guardians & teachers</h3><p>These saved local connections stay with this learner’s record and define the learner’s support team.</p></div><form id="learner-adult-team"><div class="adult-assignment-list">${adults.map(adult => `<label><input type="checkbox" value="${escapeHtml(adult.id)}" ${assigned.has(adult.id) ? 'checked' : ''}><span><strong>${escapeHtml(adult.name)}</strong><small>${escapeHtml(adult.role)}</small></span></label>`).join('')}</div><button class="os-secondary">Save profile links</button></form></section>`
}

function renderLearnerClasses(learnerId: string) {
  const classes = classesForLearner(learnerId)
  return `<section class="learner-team class-membership"><p class="os-kicker">CLASS ENROLLMENT</p><h3>Assigned classes</h3>${classes.length ? `<ul>${classes.map(group => `<li><strong>${escapeHtml(group.name)}</strong><small>${escapeHtml(group.stage)}</small></li>`).join('')}</ul>` : '<p>No class enrollment yet. An Admin assigns classes from the teacher record.</p>'}</section>`
}

function renderTeacherClasses(teacherId: string) {
  const learners = getLearners()
  const classes = classesForTeacher(teacherId)
  return `<section class="learner-team teacher-classes"><div><p class="os-kicker">TEACHING ASSIGNMENTS</p><h3>Classes & students</h3><p>Create a class once, then assign its roster to this teacher.</p></div>${classes.length ? `<ul class="class-list">${classes.map(group => `<li><span><strong>${escapeHtml(group.name)}</strong><small>${escapeHtml(group.stage)} · ${group.learnerIds.length} student${group.learnerIds.length === 1 ? '' : 's'}</small></span><button class="text-button" data-remove-class="${escapeHtml(group.id)}">Remove</button></li>`).join('')}</ul>` : '<p>No classes are assigned yet.</p>'}<form id="teacher-class-form"><label>Class name<input id="class-name" required maxlength="70" placeholder="Grade 3 Science"></label><label>Grade / stage<input id="class-stage" maxlength="40" placeholder="Grade 3"></label><div class="class-student-list"><strong>Enroll students</strong>${learners.map(learner => `<label><input type="checkbox" value="${escapeHtml(learner.id)}"><span>${escapeHtml(learner.avatar)} ${escapeHtml(learner.name)} <small>${escapeHtml(learner.ageBand)}</small></span></label>`).join('')}</div><button class="os-secondary">Create class & assign roster</button><p class="parent-error" id="class-assignment-error"></p></form></section>`
}

function wireAccountInspector(selected: AdminAccount | undefined, rerender: () => void) {
  if (selected?.kind === 'learner') wireLearnerLearningControls(selected.id, rerender)
  document.getElementById('edit-account-profile')?.addEventListener('submit', event => { event.preventDefault(); if (!selected) return; const name = (document.getElementById('profile-name') as HTMLInputElement).value; const ok = selected.kind === 'learner' ? updateLearnerProfile(selected.id, { name, ageBand: (document.getElementById('profile-stage') as HTMLInputElement).value, avatar: (document.getElementById('profile-avatar') as HTMLSelectElement).value }) : selected.kind === 'adult' ? updateAdultProfile(selected.id, { name, role: (document.getElementById('profile-role') as HTMLSelectElement).value as 'Parent' | 'Guardian' | 'Teacher' }) : false; if (ok) rerender(); else document.getElementById('profile-error')!.textContent = 'Enter the required record details.' })
  document.getElementById('selected-theme')?.addEventListener('change', event => { if (selected?.kind === 'learner') setTheme(selected.id, (event.target as HTMLSelectElement).value as never) })
  document.getElementById('learner-adult-team')?.addEventListener('submit', event => { event.preventDefault(); if (selected?.kind !== 'learner') return; const ids = [...document.querySelectorAll<HTMLInputElement>('#learner-adult-team input:checked')].map(input => input.value); setAdultsForLearner(selected.id, ids); rerender() })
  document.getElementById('teacher-class-form')?.addEventListener('submit', event => { event.preventDefault(); if (selected?.kind !== 'adult' || selected.role !== 'Teacher') return; const learnerIds = [...document.querySelectorAll<HTMLInputElement>('#teacher-class-form input[type="checkbox"]:checked')].map(input => input.value); const created = createClassGroup({ name: (document.getElementById('class-name') as HTMLInputElement).value, stage: (document.getElementById('class-stage') as HTMLInputElement).value, teacherId: selected.id, learnerIds }); if (created) rerender(); else document.getElementById('class-assignment-error')!.textContent = 'Add a class name and at least one enrolled student.' })
  document.querySelectorAll<HTMLButtonElement>('[data-remove-class]').forEach(button => button.addEventListener('click', () => { if (confirm('Remove this class and its roster assignment?')) { removeClassGroup(button.dataset.removeClass!); rerender() } }))
  document.getElementById('guardian-credentials')?.addEventListener('submit', async event => { event.preventDefault(); const ok = await updateOwnerAccount({ name: (document.getElementById('guardian-name') as HTMLInputElement).value, username: (document.getElementById('guardian-username') as HTMLInputElement).value, password: (document.getElementById('guardian-password') as HTMLInputElement).value || undefined }); if (ok) rerender(); else document.getElementById('guardian-credentials-error')!.textContent = 'Enter an account name and username; a changed password must contain at least eight characters.' })
  document.getElementById('account-credentials')?.addEventListener('submit', async event => { event.preventDefault(); if (!selected) return; const username = (document.getElementById('selected-username') as HTMLInputElement).value; const password = (document.getElementById('selected-password') as HTMLInputElement).value; const ok = selected.kind === 'learner' ? await setLearnerCredentials(selected.id, username, password) : selected.kind === 'adult' ? await setAdultCredentials(selected.id, username, password) : false; if (ok) rerender(); else document.getElementById('selected-credentials-error')!.textContent = 'Enter a username. A new password must contain at least eight characters; accounts without one need a password.' })
  document.getElementById('add-learner-account')?.addEventListener('submit', async event => { event.preventDefault(); const learner = addLearner((document.getElementById('learner-name') as HTMLInputElement).value, (document.getElementById('learner-avatar') as HTMLSelectElement).value, (document.getElementById('learner-age') as HTMLInputElement).value); if (await setLearnerCredentials(learner.id, (document.getElementById('learner-username') as HTMLInputElement).value, (document.getElementById('learner-password') as HTMLInputElement).value)) renderUserManagement('', 'learner', 'all', `learner:${learner.id}`) })
  document.getElementById('add-adult-account')?.addEventListener('submit', async event => { event.preventDefault(); await addAdult((document.getElementById('adult-name') as HTMLInputElement).value, (document.getElementById('adult-role') as HTMLSelectElement).value as 'Parent' | 'Guardian' | 'Teacher', (document.getElementById('adult-username') as HTMLInputElement).value, (document.getElementById('adult-password') as HTMLInputElement).value); rerender() })
  document.getElementById('remove-selected-learner')?.addEventListener('click', () => { if (selected?.kind === 'learner' && confirm(`Remove ${selected.name}'s local account and core activity record?`)) { removeLearner(selected.id); renderUserManagement() } })
  document.getElementById('remove-selected-adult')?.addEventListener('click', () => { if (selected?.kind === 'adult' && confirm(`Remove ${selected.name}'s staff account from this device?`)) { removeAdult(selected.id); renderUserManagement() } })
}
