export type RecipeCategory = "Breakfast" | "Lunch & Dinner" | "Snacks & Baking" | "Kitchen Foundations"

export interface HomeRecipe {
  id: string
  title: string
  category: RecipeCategory
  ages: string
  time: string
  supervision: string
  ingredients: string[]
  steps: string[]
  skill: string
  allergyNote: string
}

export const recipeCategories: RecipeCategory[] = ["Breakfast", "Lunch & Dinner", "Snacks & Baking", "Kitchen Foundations"]

export const homeRecipes: HomeRecipe[] = [
  { id: "overnight-oats", title: "Build-Your-Own Overnight Oats", category: "Breakfast", ages: "Ages 4+", time: "10 min + chill", supervision: "No heat; adult checks ingredients", ingredients: ["1/2 cup rolled oats", "1/2 cup milk or milk alternative", "1/4 cup yogurt", "Fruit or cinnamon"], steps: ["Add oats, milk, and yogurt to a jar or bowl.", "Stir until no dry oats remain.", "Add fruit or cinnamon, cover, and refrigerate overnight.", "Stir before eating and notice how the oats changed."], skill: "Measuring, mixing, and planning ahead", allergyNote: "Choose a milk and yogurt that fit household allergy needs." },
  { id: "yogurt-parfait", title: "Color-Stack Yogurt Parfait", category: "Breakfast", ages: "Ages 2+", time: "10 min", supervision: "Adult washes and cuts fruit", ingredients: ["Yogurt", "Soft fruit", "Oats or low-sugar cereal", "Optional seeds"], steps: ["Choose two or three fruit colors.", "Layer yogurt, fruit, and cereal in a cup.", "Name the pattern you made.", "Eat promptly or refrigerate."], skill: "Food groups, sequencing, and fine motor control", allergyNote: "Seeds, dairy, and cereal can be allergens; choose alternatives as needed." },
  { id: "banana-oat-pancakes", title: "Banana Oat Pancakes", category: "Breakfast", ages: "Ages 6+", time: "20 min", supervision: "Adult handles stovetop and hot pan", ingredients: ["1 ripe banana", "1 egg", "1/2 cup oats", "Pinch of cinnamon", "Oil for pan"], steps: ["Mash banana in a bowl.", "With an adult, add egg, oats, and cinnamon; stir.", "An adult cooks small scoops on a lightly oiled pan until set on both sides.", "Serve warm with fruit."], skill: "Mashing, batter texture, and heat safety", allergyNote: "Contains egg; use a household-approved alternative if needed." },
  { id: "egg-toast", title: "Egg and Toast Plate", category: "Breakfast", ages: "Ages 6+", time: "15 min", supervision: "Adult uses toaster and stove", ingredients: ["Eggs", "Bread", "Butter or spread", "Fruit or greens"], steps: ["Wash hands and gather ingredients.", "An adult cooks eggs to the preferred doneness.", "Toast bread safely with an adult.", "Build a balanced plate with fruit or greens."], skill: "Kitchen setup and safe heat boundaries", allergyNote: "Contains egg and wheat unless alternatives are used." },
  { id: "rainbow-quesadilla", title: "Rainbow Bean Quesadilla", category: "Lunch & Dinner", ages: "Ages 6+", time: "20 min", supervision: "Adult handles hot pan or oven", ingredients: ["Tortillas", "Rinsed beans", "Grated cheese or alternative", "Finely chopped bell pepper or spinach"], steps: ["Rinse beans in a colander with an adult nearby.", "Spread beans, vegetables, and cheese on one tortilla.", "Fold in half.", "An adult heats until the filling is hot and the tortilla is crisp; cut after cooling briefly."], skill: "Protein choices, rinsing, folding, and heat safety", allergyNote: "Contains dairy and wheat unless alternatives are used." },
  { id: "rice-bowl", title: "Mix-and-Match Rice Bowl", category: "Lunch & Dinner", ages: "Ages 5+", time: "20 min", supervision: "Adult cooks grains and checks food temperature", ingredients: ["Cooked rice or grain", "Beans or cooked protein", "Vegetables", "Sauce or seasoning"], steps: ["Choose one grain, one protein, and two colorful vegetables.", "Add portions to a bowl.", "With an adult, warm foods that need warming.", "Taste and describe one texture and one color."], skill: "Balanced meals and choice-making", allergyNote: "Check sauces for sesame, soy, dairy, or other allergens." },
  { id: "pita-pizza", title: "Pita Pizza Lab", category: "Lunch & Dinner", ages: "Ages 5+", time: "20 min", supervision: "Adult handles oven", ingredients: ["Pita or flatbread", "Tomato sauce", "Cheese or alternative", "Vegetable toppings"], steps: ["Spread a thin layer of sauce on pita.", "Arrange toppings in a pattern.", "An adult bakes until hot and cheese is melted.", "Cool briefly before slicing."], skill: "Spreading, portioning, and oven boundaries", allergyNote: "Check bread and cheese ingredients for allergens." },
  { id: "pasta-salad", title: "Pasta Salad Pattern Bowl", category: "Lunch & Dinner", ages: "Ages 5+", time: "25 min", supervision: "Adult drains hot pasta", ingredients: ["Cooked pasta", "Cucumber or other vegetables", "Beans or cheese", "Simple dressing"], steps: ["An adult cooks and drains pasta; let it cool.", "Chop soft ingredients with an age-appropriate tool and adult support.", "Mix pasta, vegetables, and protein.", "Add a small amount of dressing and toss."], skill: "Knife safety choices, mixing, and food cooling", allergyNote: "Check pasta, cheese, and dressing labels." },
  { id: "baked-potato-bar", title: "Baked Potato Topping Bar", category: "Lunch & Dinner", ages: "Ages 4+", time: "Adult-prepped", supervision: "Adult bakes potatoes and opens hot foods", ingredients: ["Baked potatoes", "Beans or chili", "Yogurt or cheese", "Steamed vegetables"], steps: ["An adult prepares hot potatoes.", "Set out toppings in small bowls.", "Split a cooled potato with adult help.", "Build a topping combination and name it."], skill: "Serving, portions, and meal planning", allergyNote: "Check dairy and prepared toppings." },
  { id: "apple-slices", title: "Apple Slice Sandwiches", category: "Snacks & Baking", ages: "Ages 3+", time: "10 min", supervision: "Adult cuts apples", ingredients: ["Apple slices", "Sunflower seed butter or nut butter", "Raisins or granola"], steps: ["An adult cuts apple slices safely.", "Spread a thin layer of household-approved butter on one slice.", "Add raisins or granola.", "Top with another slice."], skill: "Spreading and pattern making", allergyNote: "Use seed butter if nuts are not safe for the household." },
  { id: "no-bake-bites", title: "No-Bake Oat Bites", category: "Snacks & Baking", ages: "Ages 5+", time: "15 min + chill", supervision: "No heat; adult checks ingredients", ingredients: ["Rolled oats", "Sunflower seed butter or nut butter", "Mashed banana", "Cinnamon"], steps: ["Mash banana until smooth.", "Mix in oats, butter, and cinnamon.", "Roll small portions with clean hands.", "Chill before serving."], skill: "Mixing, portioning, and hygiene", allergyNote: "Use a safe butter and avoid honey for children under one year." },
  { id: "baked-apples", title: "Cinnamon Baked Apples", category: "Snacks & Baking", ages: "Ages 6+", time: "Adult-prepped", supervision: "Adult uses oven and cuts apples", ingredients: ["Apples", "Cinnamon", "Oats", "Small amount of butter or oil"], steps: ["An adult cores apples.", "Mix oats and cinnamon in a bowl.", "Fill apples with the oat mixture.", "An adult bakes until tender; cool before eating."], skill: "Aroma, texture, and oven safety", allergyNote: "Check butter or toppings for allergens." },
  { id: "trail-mix", title: "Trail Mix Math", category: "Snacks & Baking", ages: "Ages 3+", time: "10 min", supervision: "Adult checks choking and allergy needs", ingredients: ["Cereal", "Dried fruit", "Seeds", "Optional pretzels"], steps: ["Choose two or three safe ingredients.", "Scoop equal amounts into a bowl.", "Mix and count the colors or shapes.", "Store extras in a sealed container."], skill: "Counting, sorting, and portions", allergyNote: "Choose age-safe sizes; avoid choking hazards for young children." },
  { id: "knife-skills", title: "Safe Snack Prep Board", category: "Kitchen Foundations", ages: "Ages 6+", time: "15 min", supervision: "Adult selects tool and supervises", ingredients: ["Soft foods such as banana, berries, cheese, or cucumber", "Age-appropriate cutting tool", "Plate"], steps: ["Wash hands and make a clear workspace.", "An adult chooses a safe cutting tool.", "Use a claw hand or adult-guided technique for soft foods.", "Wash tools and wipe the workspace when done."], skill: "Tool care, cleanup, and food hygiene", allergyNote: "Choose foods appropriate for the learner." },
  { id: "seasoning-lab", title: "Seasoning Smell Lab", category: "Kitchen Foundations", ages: "Ages 3+", time: "10 min", supervision: "No heat", ingredients: ["Two or three dried herbs or spices", "Plain yogurt, rice, or vegetables to taste"], steps: ["Smell one seasoning at a time without tasting from the container.", "Describe the smell with a color, memory, or word.", "Add a tiny amount to a shared food with adult approval.", "Record which combination you liked."], skill: "Sensory vocabulary and respectful tasting", allergyNote: "Check for individual food sensitivities." },
  { id: "fridge-map", title: "Refrigerator Map", category: "Kitchen Foundations", ages: "Ages 4+", time: "10 min", supervision: "Adult guides food handling", ingredients: ["Paper", "Pencil", "Closed refrigerator"], steps: ["With an adult, look at where foods are stored.", "Draw shelves and label ready-to-eat foods and ingredients.", "Choose one leftover to ask about before eating.", "Close the refrigerator promptly."], skill: "Food storage awareness and planning", allergyNote: "Do not taste or handle unknown leftovers." },
]

export interface HomeCareGuide { id: string; category: "Cleaning" | "Laundry" | "Home care" | "Pet safety" | "Canning"; title: string; whatItTeaches: string; childRole: string; adultRole: string; never: string[] }

export const homeCareGuides: HomeCareGuide[] = [
  { id: "reset-room", category: "Home care", title: "Ten-Minute Room Reset", whatItTeaches: "A calm space is built through small routines: return, wipe, sort, and notice what needs adult help.", childRole: "Put away toys, match socks, wipe a table with plain water and a clean cloth.", adultRole: "Handle chemicals, heavy items, sharp objects, and high shelves.", never: ["Never climb furniture to reach items.", "Never use a cleaner unless a grown-up gives it to you."] },
  { id: "dishes", category: "Home care", title: "Dishwashing Flow", whatItTeaches: "Cleaning works best when food is scraped, dishes are sorted, washed, rinsed, and dried in order.", childRole: "Scrape plates, sort utensils, wash unbreakable items in warm soapy water with adult support.", adultRole: "Handle knives, glass, very hot water, and dishwasher chemicals.", never: ["Never put a hand into cloudy dishwater where a sharp item may be hidden.", "Never mix dish soap with another cleaner."] },
  { id: "laundry-sort", category: "Laundry", title: "Laundry Sorting and Care", whatItTeaches: "Fabric labels, color, and soil level guide a laundry plan.", childRole: "Sort clean-safe clothing by color, match socks, fold towels, and set a timer with help.", adultRole: "Measure detergent, handle stain products, operate machines, and store products.", never: ["Never play in or climb into a washer or dryer.", "Never touch laundry pods, bleach, or stain remover."] },
  { id: "spot-test", category: "Laundry", title: "Stain Detective", whatItTeaches: "The safest stain treatment starts with identifying the fabric and reading the garment and product labels.", childRole: "Name the stain, check a care label with an adult, and help blot with plain water when approved.", adultRole: "Choose treatment and test it in a hidden area.", never: ["Never combine bleach, ammonia, acids, or stain products.", "Never use a product from an unlabelled container."] },
  { id: "pet-zone", category: "Pet safety", title: "Pet-Safe Home Check", whatItTeaches: "Pets explore with mouths, paws, and noses, so storage and dry surfaces matter.", childRole: "Pick up food scraps and toys, close doors, and tell an adult about a spill.", adultRole: "Read product labels, keep pets away during cleaning, and contact a veterinarian for possible exposure.", never: ["Never give pets human food or medicine without veterinary advice.", "Never try to make a pet vomit unless a veterinarian or poison expert tells you to."] },
  { id: "canning-helper", category: "Canning", title: "Canning Helper Jobs", whatItTeaches: "Home canning uses tested recipes and exact methods because food acidity, temperature, jar size, altitude, and processing time affect safety.", childRole: "Make labels, count clean jars from a distance, sort cool produce, and record a tested recipe name.", adultRole: "Choose a current tested recipe, operate canning equipment, handle hot jars, and decide processing method.", never: ["Never use an untested recipe or change jar size, acidity, or processing time.", "Never use oven, microwave, or open-kettle canning methods."] },
]

export const cleaningIngredients = [
  { name: "Soap and dish detergent", property: "Surfactants lift oils and soil so water can carry them away.", bestFor: "Routine dishwashing and washable surfaces when used as labeled.", safety: "Keep in the original container; do not mix with other cleaners." },
  { name: "Baking soda", property: "A mild abrasive that can help with gentle scrubbing and odors.", bestFor: "Adult-approved scrubbing tasks such as a sink or baking dish.", safety: "It is not a replacement for a labeled disinfectant when disinfection is needed." },
  { name: "White vinegar", property: "A mild acid that can help loosen mineral deposits and soap film.", bestFor: "Adult-approved hard-water spots and soap scum.", safety: "Never mix with bleach or other cleaners; keep away from natural stone unless the manufacturer says it is safe." },
  { name: "Hydrogen peroxide products", property: "Some labeled products oxidize stains or disinfect on specific surfaces.", bestFor: "Only the exact uses and contact time listed on the label.", safety: "Use adult handling, ventilation, and label directions; never mix cleaners." },
  { name: "Bleach and strong cleaners", property: "Some products disinfect or remove stains but can irritate or burn skin, eyes, and lungs.", bestFor: "Only adult-selected, label-directed use.", safety: "Never mix with any other cleaner. Keep children and pets away until the area is rinsed or dry as the label directs." },
]

export const petSafetyFacts = [
  "Keep chocolate, grapes and raisins, xylitol-containing products, onions, garlic, alcohol, and raw yeast dough away from pets.",
  "Store cleaners, medicines, batteries, and pesticides in original containers and out of reach.",
  "Keep pets out of rooms while strong cleaners are used; follow the product label and allow cleaned areas to dry before return.",
  "Birds can be especially sensitive to fumes. Ask a veterinarian before using cleaning products around them.",
  "If a pet may have been exposed, contact a veterinarian or ASPCA Animal Poison Control at 888-426-4435 promptly; do not wait for symptoms or induce vomiting unless told to do so.",
]

export const canningSafety = [
  "Use a current, tested recipe from the National Center for Home Food Preservation or an extension service; do not invent processing times.",
  "The method depends on the food and tested recipe. Low-acid foods require pressure canning; acid foods use the method specified by the tested recipe.",
  "Altitude, jar size, preparation style, and processing time are part of the safety instructions, not optional details.",
  "Use clean, sound jars and equipment as directed by the recipe. A sealed lid alone does not prove food is safe.",
  "When in doubt about a home-canned food, do not taste it. Discard it safely and ask an extension professional for guidance.",
]
