export type K12Grade = 'kindergarten' | `grade-${string}`

export const k12Grades: Array<{ id: K12Grade; label: string; shortLabel: string }> = [
  { id: 'kindergarten', label: 'Kindergarten', shortLabel: 'K' },
  ...Array.from({ length: 12 }, (_, index) => {
    const grade = index + 1
    return { id: `grade-${String(grade).padStart(2, '0')}` as K12Grade, label: `Grade ${grade}`, shortLabel: String(grade) }
  }),
]

export type K12ModuleSubject = {
  id: string
  name: string
  icon: string
  color: string
  framework: string
  frameworkUrl?: string
  summary: string
  semesters: [string, string]
}

// The visual shelf is a local index of the K–12 manifest scaffold. It deliberately
// presents standards and retrieval paths without automatically opening the web.

export const hobbyModuleSubjects: K12ModuleSubject[] = [
  { id: 'fiber-arts', name: 'Fiber Arts', icon: '🧶', color: '#a85d86', framework: 'Skill pathway · family/teacher-directed', summary: 'Crochet, knitting, weaving, embroidery, hand sewing, and textile care.', semesters: ['Stitch, loop & pattern', 'Design, make & mend'] },
  { id: 'drawing-and-illustration', name: 'Drawing & Illustration', icon: '✏️', color: '#6a6d80', framework: 'National Core Arts Standards', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Sketching, observation, line, value, visual storytelling, and portfolio practice.', semesters: ['Observe, sketch & see', 'Illustrate, revise & share'] },
  { id: 'painting-and-mixed-media', name: 'Painting & Mixed Media', icon: '🖌️', color: '#d35370', framework: 'National Core Arts Standards', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Color, paint handling, collage, printmaking, mixed media, and creative choices.', semesters: ['Color, mark & explore', 'Compose, layer & exhibit'] },
  { id: 'ceramics-and-sculpture', name: 'Ceramics & Sculpture', icon: '🏺', color: '#af714e', framework: 'National Core Arts Standards', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Clay, form, texture, sculpture, safe tools, and three-dimensional design.', semesters: ['Form, texture & tools', 'Build, fire & present'] },
  { id: 'photography-and-film', name: 'Photography & Film', icon: '📷', color: '#4b7186', framework: 'National Core Arts Standards + media literacy', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Camera craft, composition, visual storytelling, editing, and ethical media making.', semesters: ['Frame, light & notice', 'Story, edit & screen'] },
  { id: 'digital-art-and-design', name: 'Digital Art & Design', icon: '🖥️', color: '#5572bd', framework: 'National Core Arts Standards + ISTE Students', frameworkUrl: 'https://iste.org/standards/students', summary: 'Digital drawing, graphic design, typography, animation, and respectful publishing.', semesters: ['Design tools & visual voice', 'Create, revise & publish'] },
  { id: 'woodworking', name: 'Woodworking', icon: '🪵', color: '#8a613e', framework: 'Skill pathway · safety-first', summary: 'Measuring, joinery, safe hand tools, finishing, repair, and useful projects.', semesters: ['Measure, plan & build', 'Join, finish & repair'] },
  { id: 'metalwork-and-jewelry', name: 'Metalwork & Jewelry', icon: '💍', color: '#7a7e91', framework: 'Skill pathway · safety-first', summary: 'Wirework, simple metal shaping, jewelry design, wearable art, and safe tools.', semesters: ['Shape, connect & design', 'Craft, refine & present'] },
  { id: 'fashion-and-textile-design', name: 'Fashion & Textile Design', icon: '👗', color: '#bd6287', framework: 'Family & Consumer Sciences', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Fabric, patterns, garment design, mending, styling, and responsible materials.', semesters: ['Fabric, fit & function', 'Pattern, make & wear'] },
  { id: 'robotics-and-electronics', name: 'Robotics & Electronics', icon: '🤖', color: '#387c93', framework: 'CSTA + ISTE Students', frameworkUrl: 'https://csteachers.org/k12standards/', summary: 'Circuits, sensors, control systems, coding, testing, and responsible invention.', semesters: ['Circuits, code & control', 'Build, test & improve'] },
  { id: 'maker-and-3d-design', name: 'Maker & 3D Design', icon: '🧩', color: '#5b6c9e', framework: 'NGSS Engineering Design', frameworkUrl: 'https://www.nextgenscience.org/resources/appendix-i-engineering-design-ngss', summary: 'Cardboard engineering, models, CAD ideas, 3D making, prototypes, and iteration.', semesters: ['Imagine, model & prototype', 'Make, test & improve'] },
  { id: 'culinary-arts-and-baking', name: 'Culinary Arts & Baking', icon: '🧁', color: '#bf7544', framework: 'Family & Consumer Sciences + safety', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Kitchen safety, recipes, nutrition, baking science, food culture, and hospitality.', semesters: ['Prepare, measure & taste', 'Cook, adapt & host'] },
  { id: 'nutrition-and-food-science', name: 'Nutrition & Food Science', icon: '🥗', color: '#689c58', framework: 'Family & Consumer Sciences + health literacy', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Food groups, nutrients, labels, food systems, energy, and evidence-informed everyday nourishment.', semesters: ['Nourish, notice & investigate', 'Plan, evaluate & advocate'] },
  { id: 'healthy-cooking', name: 'Healthy Cooking', icon: '🍲', color: '#d4874d', framework: 'Family & Consumer Sciences + kitchen safety', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Safe, joyful, budget-aware cooking with whole foods, flexible recipes, food culture, and shared meals.', semesters: ['Safe kitchen, simple meals', 'Balance, adapt & share'] },
  { id: 'home-economics-and-life-skills', name: 'Home Economics & Life Skills', icon: '🏠', color: '#7c8fca', framework: 'Family & Consumer Sciences', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Home care, budgeting, food planning, textiles, consumer choices, relationships, and practical independence.', semesters: ['Care for self, home & resources', 'Plan, provide & participate'] },
  { id: 'recipe-studio-and-food-culture', name: 'Recipe Studio & Food Culture', icon: '📖', color: '#b96c66', framework: 'Family & Consumer Sciences + cultural literacy', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Collect, read, write, adapt, and share recipes while exploring family stories, ingredients, and global food traditions.', semesters: ['Read, collect & create recipes', 'Adapt, document & celebrate food stories'] },
  { id: 'animal-care', name: 'Animal Care & Horsemanship', icon: '🐴', color: '#8b6b52', framework: 'Skill pathway · welfare-first', summary: 'Animal welfare, observation, habitat care, responsible routines, and horsemanship foundations.', semesters: ['Observe, care & respect', 'Train, steward & explain'] },
  { id: 'outdoor-adventure', name: 'Outdoor Adventure', icon: '🏕️', color: '#477c57', framework: 'Environmental education + safety', frameworkUrl: 'https://naaee.org/eepro/resources/guidelines-excellence', summary: 'Hiking, camping readiness, navigation, weather, leave-no-trace habits, and outdoor confidence.', semesters: ['Prepare, navigate & notice', 'Explore, lead & steward'] },
  { id: 'fishing-and-water-skills', name: 'Fishing & Water Skills', icon: '🎣', color: '#31799e', framework: 'Skill pathway · water safety-first', summary: 'Water safety, aquatic ecosystems, fishing practice, knots, stewardship, and local rules.', semesters: ['Water, knots & habitat', 'Fish, steward & share'] },
  { id: 'archery-and-target-sports', name: 'Archery & Target Sports', icon: '🏹', color: '#a46c31', framework: 'Skill pathway · certified supervision required', summary: 'Focus, range rules, safe equipment habits, body awareness, and goal setting.', semesters: ['Safety, stance & focus', 'Practice, score & reflect'] },
  { id: 'gymnastics-and-dance', name: 'Gymnastics & Dance', icon: '🤸', color: '#8a5bb1', framework: 'SHAPE America + National Core Arts', frameworkUrl: 'https://apeas.shapeamerica.org/APEAS3/standards/pe/new-pe-standards.aspx', summary: 'Balance, flexibility, locomotor skill, choreography, safe progression, and performance.', semesters: ['Balance, move & express', 'Sequence, perform & grow'] },
  { id: 'team-sports', name: 'Team Sports', icon: '🏀', color: '#c27029', framework: 'SHAPE America National PE Standards', frameworkUrl: 'https://apeas.shapeamerica.org/APEAS3/standards/pe/new-pe-standards.aspx', summary: 'Sport skills, teamwork, strategy, sportsmanship, officiating, and healthy practice habits.', semesters: ['Skills, rules & teamwork', 'Strategy, leadership & play'] },
  { id: 'individual-sports-and-fitness', name: 'Individual Sports & Fitness', icon: '🏃', color: '#3e8b6c', framework: 'SHAPE America National PE Standards', frameworkUrl: 'https://apeas.shapeamerica.org/APEAS3/standards/pe/new-pe-standards.aspx', summary: 'Running, cycling, racquet sports, strength, fitness planning, and personal goals.', semesters: ['Move, train & track', 'Challenge, recover & sustain'] },
  { id: 'martial-arts', name: 'Martial Arts', icon: '🥋', color: '#5a6388', framework: 'Skill pathway · qualified instruction', summary: 'Respect, movement forms, balance, self-control, safe practice, and personal discipline.', semesters: ['Respect, stance & control', 'Form, practice & reflect'] },
  { id: 'skateboarding-and-cycling', name: 'Skateboarding & Cycling', icon: '🛹', color: '#4c86a7', framework: 'Skill pathway · safety-first', summary: 'Balance, protective gear, maintenance, traffic awareness, progression, and community riding.', semesters: ['Safety, balance & basics', 'Maintain, navigate & progress'] },
  { id: 'chess-and-strategy-games', name: 'Chess & Strategy Games', icon: '♟️', color: '#615a7c', framework: 'Strategy pathway · family/teacher-directed', summary: 'Chess, logic games, planning ahead, pattern recognition, fair play, and reflection.', semesters: ['Patterns, rules & tactics', 'Plan, analyze & compete'] },
  { id: 'tabletop-game-design', name: 'Tabletop Game Design', icon: '🎲', color: '#9a5e91', framework: 'Design pathway · family/teacher-directed', summary: 'Rules, probability, storytelling, prototyping, playtesting, and accessible game design.', semesters: ['Rules, chance & prototypes', 'Playtest, revise & publish'] },
  { id: 'model-building-and-miniatures', name: 'Model Building & Miniatures', icon: '🚂', color: '#727f58', framework: 'Maker pathway · safety-first', summary: 'Scale, research, construction, painting, terrain, patience, and detailed craftsmanship.', semesters: ['Scale, plan & assemble', 'Detail, display & explain'] },
  { id: 'theater-and-improv', name: 'Theater & Improv', icon: '🎭', color: '#a64860', framework: 'National Core Arts Standards', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Voice, movement, character, collaboration, improv, technical theater, and performance.', semesters: ['Play, voice & character', 'Rehearse, perform & reflect'] },
  { id: 'debate-and-public-speaking', name: 'Debate & Public Speaking', icon: '🎙️', color: '#476b9f', framework: 'National Speech & Debate Association resources', frameworkUrl: 'https://www.speechanddebate.org/competition-events/', summary: 'Research, listening, argument, speech craft, respectful disagreement, and audience awareness.', semesters: ['Speak, listen & support claims', 'Research, debate & present'] },
  { id: 'languages-and-culture', name: 'Languages & Culture', icon: '🗣️', color: '#4f8a78', framework: 'ACTFL World-Readiness Standards', frameworkUrl: 'https://www.actfl.org/educator-resources/world-readiness-standards-for-learning-languages', summary: 'Communication, culture, connection, comparison, and communities through language learning.', semesters: ['Communicate & connect', 'Create, compare & participate'] },
  { id: 'financial-literacy-and-entrepreneurship', name: 'Financial Literacy & Entrepreneurship', icon: '💡', color: '#8b752f', framework: 'Jump$tart National Standards', frameworkUrl: 'https://jumpstart.org/national-standards/', summary: 'Earning, saving, budgeting, enterprise, ethical choices, and community value.', semesters: ['Money, choices & value', 'Plan, launch & reflect'] },
  { id: 'automotive-and-mechanics', name: 'Automotive & Mechanics', icon: '🔩', color: '#67768a', framework: 'Skill pathway · adult supervision required', summary: 'Tools, simple machines, maintenance, diagnostics, repair thinking, and shop safety.', semesters: ['Tools, systems & safety', 'Maintain, diagnose & repair'] },
  { id: 'home-repair-and-diy', name: 'Home Repair & DIY', icon: '🪛', color: '#9b704d', framework: 'Skill pathway · safety-first', summary: 'Household repair, measuring, basic tools, planning, maintenance, and responsible making.', semesters: ['Tools, measure & maintain', 'Repair, improve & contribute'] },
  { id: 'aviation-and-flight', name: 'Aviation & Flight', icon: '✈️', color: '#4b7fa4', framework: 'STEM pathway · safety-first', summary: 'Flight, weather, navigation, model aircraft, aerospace systems, and aviation careers.', semesters: ['Lift, weather & navigation', 'Design, fly & investigate'] },
]

export const explorationModuleSubjects: K12ModuleSubject[] = [
  { id: 'world-religions-and-belief', name: 'World Religions & Belief', icon: '🌍', color: '#7a638c', framework: 'Academic, comparative, non-devotional study', summary: 'Respectful study of worldviews, traditions, lived experience, ethics, and the difference between learning about and practicing a belief.', semesters: ['Questions, traditions & respectful inquiry', 'Texts, lived experience & dialogue'] },
  { id: 'world-politics-and-global-affairs', name: 'World Politics & Global Affairs', icon: '🕊️', color: '#496b9d', framework: 'C3 inquiry + civic media literacy', frameworkUrl: 'https://www.socialstudies.org/standards/c3', summary: 'Governance, global systems, current-event literacy, multiple perspectives, diplomacy, and evidence-based discussion.', semesters: ['Systems, voices & perspectives', 'Issues, diplomacy & civic action'] },
  { id: 'travel-and-global-citizenship', name: 'Travel & Global Citizenship', icon: '🧳', color: '#468583', framework: 'Geography + cultural literacy', summary: 'Maps, planning, languages, respectful travel, culture, geography, accessibility, and responsible global citizenship.', semesters: ['Place, planning & preparation', 'Culture, exchange & reflection'] },
  { id: 'antiques-and-material-culture', name: 'Antiques & Material Culture', icon: '🪑', color: '#906c4f', framework: 'Historical inquiry · family/teacher-directed', summary: 'Objects as evidence: provenance, design, craftsmanship, care, ethical collecting, history, and family stories.', semesters: ['Objects, stories & provenance', 'Research, care & interpretation'] },
  { id: 'coins-and-collectibles', name: 'Coins & Collectibles', icon: '🪙', color: '#927844', framework: 'History + financial literacy · family/teacher-directed', summary: 'Coins, stamps, trading cards, collections, cataloging, condition, value, ethics, and the stories objects carry.', semesters: ['Collect, classify & investigate', 'Catalog, compare & curate'] },
  { id: 'archaeology-and-museum-studies', name: 'Archaeology & Museum Studies', icon: '🗿', color: '#7d6a55', framework: 'C3 inquiry + ethical stewardship', frameworkUrl: 'https://www.socialstudies.org/standards/c3', summary: 'Artifacts, excavation ethics, preservation, interpretation, museum design, repatriation, and public history.', semesters: ['Evidence, artifacts & stewardship', 'Interpret, exhibit & question'] },
  { id: 'journalism-and-media-studies', name: 'Journalism & Media Studies', icon: '📰', color: '#4d6f85', framework: 'Media literacy + journalism ethics', summary: 'Research, interviewing, source evaluation, news craft, photography, editing, misinformation, and responsible publication.', semesters: ['Ask, verify & report', 'Edit, publish & reflect'] },
  { id: 'environmental-stewardship', name: 'Environmental Stewardship', icon: '🌎', color: '#43865a', framework: 'NAAEE + NGSS', frameworkUrl: 'https://naaee.org/eepro/resources/guidelines-excellence', summary: 'Climate, ecology, conservation, community science, systems thinking, and informed local action.', semesters: ['Observe systems & impacts', 'Steward, design & contribute'] },
  { id: 'anatomy-and-physiology', name: 'Anatomy & Physiology', icon: '🫀', color: '#a6565e', framework: 'NGSS life science + health literacy', frameworkUrl: 'https://www.nextgenscience.org/standards', summary: 'Age-appropriate study of body systems, structure and function, growth, health information, and respectful scientific observation.', semesters: ['Body systems, structure & function', 'Regulation, health & human variation'] },
  { id: 'exercise-science', name: 'Exercise Science', icon: '💪', color: '#3c7d6c', framework: 'SHAPE America + health literacy', frameworkUrl: 'https://apeas.shapeamerica.org/APEAS3/standards/pe/new-pe-standards.aspx', summary: 'Movement, training principles, recovery, biomechanics, fitness data, and lifelong physical wellbeing.', semesters: ['Move, measure & understand', 'Train, recover & apply'] },
]
export const k12ModuleSubjects: K12ModuleSubject[] = [
  { id: 'early-learning', name: 'Early Learning', icon: '🌱', color: '#3e8b6c', framework: 'Head Start ELOF + local K standards', frameworkUrl: 'https://headstart.gov/school-readiness/effective-practice-guides/effective-practice-guides', summary: 'Playful readiness, language, number, movement, and belonging.', semesters: ['Roots & routines', 'Stories & growing independence'] },
  { id: 'music', name: 'Music', icon: '🎵', color: '#8d4db5', framework: 'National Core Arts Standards', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Create, perform, respond, and connect through sound.', semesters: ['Listen, sing & make', 'Perform, compose & connect'] },
  { id: 'beginner-coding', name: 'Beginner Coding', icon: '💻', color: '#326cc3', framework: 'CSTA + ISTE Students', frameworkUrl: 'https://csteachers.org/k12standards/', summary: 'Computational thinking, code, design, and digital citizenship.', semesters: ['Patterns & instructions', 'Projects & problem solving'] },
  { id: 'mathematics', name: 'Mathematics', icon: '➗', color: '#197a92', framework: 'Common Core Mathematics', frameworkUrl: 'https://corestandards.org/mathematics-standards/', summary: 'Coherent concepts, procedures, reasoning, and real-world problems.', semesters: ['Build understanding', 'Apply, explain & extend'] },
  { id: 'reading', name: 'Reading', icon: '📚', color: '#b15b34', framework: 'Common Core ELA/Literacy', frameworkUrl: 'https://corestandards.org/english-language-arts-standards/', summary: 'Read closely, build knowledge, and respond to meaningful texts.', semesters: ['Stories & meaning', 'Knowledge & craft'] },
  { id: 'science', name: 'Science', icon: '🔬', color: '#287355', framework: 'Next Generation Science Standards', frameworkUrl: 'https://www.nextgenscience.org/standards', summary: 'Three-dimensional inquiry through phenomena, evidence, and design.', semesters: ['Wonder, investigate & model', 'Explain, design & communicate'] },
  { id: 'history', name: 'History', icon: '🏛️', color: '#77524b', framework: 'C3 Framework + state standards', frameworkUrl: 'https://www.socialstudies.org/standards/c3', summary: 'Questions, evidence, perspective, and historical argument.', semesters: ['People, sources & change', 'Evidence, claims & civic stories'] },
  { id: 'geography', name: 'Geography', icon: '🗺️', color: '#26826b', framework: 'C3 Geography Dimension + state standards', frameworkUrl: 'https://www.socialstudies.org/standards/c3', summary: 'Place, maps, systems, and human-environment connections.', semesters: ['Where we are', 'Places, systems & connections'] },
  { id: 'language-arts', name: 'Language Arts', icon: '✍️', color: '#c05a7e', framework: 'Common Core ELA/Literacy', frameworkUrl: 'https://corestandards.org/english-language-arts-standards/', summary: 'Reading, writing, speaking, listening, and language as one practice.', semesters: ['Read, write & share', 'Research, revise & publish'] },
  { id: 'art-and-creativity', name: 'Art & Creativity', icon: '🎨', color: '#b2517d', framework: 'National Core Arts Standards', frameworkUrl: 'https://www.nationalartsstandards.org/content/national-core-arts-standards', summary: 'Create, present, respond, and connect across visual and media arts.', semesters: ['Explore materials & ideas', 'Create, present & reflect'] },
  { id: 'physical-education', name: 'Physical Education', icon: '⚽', color: '#ce7d22', framework: 'SHAPE America National PE Standards', frameworkUrl: 'https://apeas.shapeamerica.org/APEAS3/standards/pe/new-pe-standards.aspx', summary: 'Physical literacy, movement confidence, health, and lifelong activity.', semesters: ['Move with confidence', 'Play, care & persist'] },
  { id: 'engineering', name: 'Engineering', icon: '🛠️', color: '#52708e', framework: 'NGSS Engineering Design', frameworkUrl: 'https://www.nextgenscience.org/resources/appendix-i-engineering-design-ngss', summary: 'Define problems, test ideas, and improve solutions.', semesters: ['Ask, imagine & prototype', 'Test, improve & explain'] },
  { id: 'living-library', name: 'Living Library', icon: '🔎', color: '#254a49', framework: 'AASL National School Library Standards', frameworkUrl: 'https://standards.aasl.org/framework/', summary: 'Inquiry, inclusion, curation, exploration, and ethical engagement.', semesters: ['Question & curate', 'Create, share & reflect'] },
  { id: 'homestead-lab', name: 'Homestead Lab', icon: '🏠', color: '#8a653e', framework: 'Family & Consumer Sciences + safety guidance', frameworkUrl: 'https://www.nasafacs.org/national-standards-overview.html', summary: 'Safe real-life routines, care, food, home, and responsibility.', semesters: ['Care for home & self', 'Plan, prepare & contribute'] },
  { id: 'learning-commons', name: 'Learning Commons', icon: '🤝', color: '#5661a8', framework: 'AASL + ISTE Students', frameworkUrl: 'https://standards.aasl.org/framework/', summary: 'Research, collaboration, media literacy, and learning strategies.', semesters: ['Ask, find & evaluate', 'Make, share & improve'] },
  { id: 'gardening', name: 'Gardening', icon: '🌻', color: '#54833c', framework: 'NAAEE + NGSS', frameworkUrl: 'https://naaee.org/eepro/resources/guidelines-excellence', summary: 'Seasonal observation, living systems, stewardship, and food.', semesters: ['Observe & plan', 'Grow, tend & reflect'] },
  { id: 'mindful-movement', name: 'Mindful Movement', icon: '🧘', color: '#6e6bb3', framework: 'CASEL + SHAPE (supporting guides)', frameworkUrl: 'https://casel.org/fundamentals-of-sel/', summary: 'Optional, non-clinical movement, awareness, regulation, and care.', semesters: ['Notice body & breath', 'Move, reset & care'] },
  { id: 'spirit', name: 'Spirit', icon: '✨', color: '#9b6a31', framework: 'Family-directed scope and sequence', summary: 'Optional family-guided reflection, traditions, ethics, and meaning.', semesters: ['Wonder & belonging', 'Practice & reflection'] },
  ...hobbyModuleSubjects,
  ...explorationModuleSubjects,
]

export type UnitBlueprint = { id: string; title: string; essentialQuestion: string; lessonFocus: string }

export function unitBlueprintFor(grade: K12Grade, subject: K12ModuleSubject, semester: 1 | 2): UnitBlueprint[] {
  const semesterTitle = subject.semesters[semester - 1]
  const gradeLabel = k12Grades.find(item => item.id === grade)?.label ?? "This grade"
  return [
    { id: "u01", title: "Launch: " + semesterTitle, essentialQuestion: "What does " + gradeLabel + " " + subject.name + " invite us to notice and wonder?", lessonFocus: "Notice, name prior knowledge, and set a meaningful question." },
    { id: "u02", title: "Explore & practice", essentialQuestion: "How do we build skill and understanding in " + subject.name + "?", lessonFocus: "Learn through models, guided practice, and feedback." },
    { id: "u03", title: "Create & apply", essentialQuestion: "How can we use " + subject.name + " to make, solve, or contribute?", lessonFocus: "Apply learning in a STEM, fine-art, or real-world creation." },
    { id: "u04", title: "Reflect & share", essentialQuestion: "What evidence shows growth, and what should happen next?", lessonFocus: "Share evidence, reflect, request help when needed, and set a next step." },
  ]
}

export function moduleIdFor(grade: K12Grade, subjectId: string, semester: 1 | 2) {
  return `${grade}-${subjectId}-semester-${String(semester).padStart(2, '0')}`
}
